# Generated by Django 2.2.2 on 2021-05-08 16:36

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210508_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=blog.models.upload_location),
        ),
    ]
