# Generated by Django 2.2.2 on 2021-03-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210325_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
