# Generated by Django 2.2.2 on 2021-05-02 06:25

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to=account.models.upload_location),
        ),
    ]
