# Generated by Django 2.2.2 on 2021-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='karma',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
