# Generated by Django 2.2.2 on 2021-05-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210506_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='karma',
        ),
    ]
